### ISSUE TITLE
Does not work properly under Windows

### ISSUE THREAD

**Issue by ghost** [paulsm/pyzeroconf#1]
The demo file crashes while getting service info on Windows 7 x64. 

I will test and report further when I get a chance. This is probably related to some of the limitations of Python sockets under Windows.

**Comment by paulsm** [comment]
Thanks for the report, but I'm unlikely to do much about this as pyzeroconf is not the right way to do mDNS (you really need a single daemon process per host that responds to queries, rather than a potential multitude of processes that maintain their own state and responses).  I'd advise you to look into python bindings for one of the other implementations that provide a daemon to share amongst processes.

--Paul
